
[functions.generate-caption]
enabled = true
verify_jwt = false
import_map = "./functions/generate-caption/deno.json"
entrypoint = "./functions/generate-caption/index.ts"

[functions.iyzico-payment]
enabled = true

[functions.iyzico-payment-callback]
enabled = true
verify_jwt = false
